---
- name: Configure the message of the day
  hosts: all
  remote_user: devops
  become: true
  vars:
    - system_owner: clyde@example.com
  tasks:
    - name: Configure /etc/mote
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/mote
        owner: root
        group: root
        mode: 0644
